---
- name: Copy autoinstall templates
  ansible.builtin.template:
    src: "templates/{{ item }}.j2"
    dest: "/var/lib/cobbler/templates/{{ item }}"
  loop:
    - debian.seed
    - rhel.ks

- name: Copy custom autoinstall templates
  ansible.builtin.copy:
    content: "{{ item.content }}"
    dest: "/var/lib/cobbler/templates/{{ item.name }}"
  loop: "{{ cobbler_autoinstall_templates }}"
  loop_control:
    label: "{{ item.name }}"
  when: cobbler_autoinstall_templates | length > 0

- name: Copy snippets
  ansible.builtin.template:
    src: "snippets/{{ item }}.j2"
    dest: "/var/lib/cobbler/snippets/{{ item }}"
  loop:
    - create_automation_user

- name: Do not configure apt repo in preseed late script
  ansible.builtin.lineinfile:
    path: /var/lib/cobbler/scripts/preseed_late_default
    state: absent
    regexp: 'late_apt_repo_config'

- name: Add snippet to create automation user in preseed late script
  ansible.builtin.lineinfile:
    path: /var/lib/cobbler/scripts/preseed_late_default
    insertbefore: 'autoinstall_done'
    line: $SNIPPET('create_automation_user')
    create: yes

- name: Configure Cobbler profiles
  cobbler_profile:
    host: "{{ cobbler_api_host }}"
    use_ssl: "{{ cobbler_api_use_ssl | default(omit) }}"
    username: "{{ cobbler_api_username }}"
    password: "{{ cobbler_api_password }}"
    name: "{{ item.name }}"
    state: "{{ item.state | default(omit) }}"
    properties: "{{ item.properties }}"
  delegate_to: localhost
  become: false
  loop: "{{ cobbler_profiles }}"
  loop_control:
    label: "{{ item.name }}"
