---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "quay.io/actatux/${MOLECULE_DISTRO:-debian-systemd:bullseye}"
    override_command: false
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
