---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: quay.io/actatux/debian-systemd:bullseye
    override_command: false
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
